### ISSUE TITLE
win32job 1.0.3 is a breaking change

### ISSUE THREAD

**Issue by sunshowers** [ohadravid/win32job-rs#3]
Thanks again for maintaining this crate!

I really appreciate the update to 1.0.3 which switched away from winapi. Sadly, however, the update to 1.0.3 is a breaking change. In particular, methods like [`Job::handle`](https://docs.rs/win32job/latest/win32job/struct.Job.html#method.handle) return a `HANDLE`, for which the definition has changed to a [`windows` HANDLE](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HANDLE.html), which is a newtype around an isize rather than an isize itself.

For an example breakage, see: https://github.com/nextest-rs/nextest/actions/runs/7640446319/job/20815588102?pr=1247

(And technically, a 1.x crate should not be exporting a dependency's 0.x public type in the first place.)

To address this issue, I'm wondering if as part of a 2.0.0 upgrade we can just change the API to `isize`, or define our own `HANDLE` type alias or newtype here. Users can do their own work to convert it to a `windows` HANDLE or any other HANDLE type of their choosing, which hopefully isn't too onerous.

**Comment by sunshowers** [comment]
Ah there's also `ExtendedLimitInfo` here: https://docs.rs/win32job/latest/win32job/struct.ExtendedLimitInfo.html

Hmmm, maybe this crate should just embrace being tied to a particular `windows` version in that case.

**Comment by ohadravid** [comment]
😨  yanked! Will take a closer look later

**Comment by ohadravid** [comment]
> change the API to isize, or define our own HANDLE type

I think that would be the best thing, something like:

```
struct Handle(pub isize);

impl From<windows::Win32::Foundation::HANDLE> for Handle { ... }
impl From<*mut c_void> for Handle { ... }

fn assign_process(&self, proc_handle: impl Into<Handle>) { ... }
```

which shouldn't be breaking for the code in the link (but might still be considered a breaking change? I don't remember if there's some subtlety with `Type -> impl Into<Type>` changes)

For `handle()` and `into_handle()`, it's possible to return `*mut c_void` which avoid breaking anything.

> ExtendedLimitInfo

Yes, that one is more problematic.

The reason I exposed the inner type is so that other limits can be used which aren't implemented in this crate.

I'm not sure what's the best thing to do in this case.

> being tied to a particular windows version in that case.

The `windows` create is actually very unstable (API-wise) [for very good reasons!], so it doesn't really make sense for this crate I think.

The [JOBOBJECT_EXTENDED_LIMIT_INFORMATION](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/JobObjects/struct.JOBOBJECT_EXTENDED_LIMIT_INFORMATION.html) there is useful, so it's possible to change the field to private and maybe add `as_ref/as_mut` under a feature flag?

I'd love to hear your opinion @sunshowers (as possibly the main user of this crate 😉 )

**Comment by sunshowers** [comment]
> impl From<windows::Win32::Foundation::HANDLE> for Handle { ... }

In its current form this would be a public API, because if this crate's `windows` version is updated then existing code depending on `windows` 0.52 would break. I think we'll need users to do any conversion manually.

**However:** Instead of the windows crate I believe we can use the lower-level windows-sys crate. With that crate, a [HANDLE](https://docs.rs/windows-sys/0.52.0/windows_sys/Win32/Foundation/type.HANDLE.html) is just an isize. windows-sys is quicker to compile anyway, and just slightly less ergonomic (more similar to winapi).

> impl From<*mut c_void> for Handle { ... }

This would be fine.

> which shouldn't be breaking for the code in the link (but might still be considered a breaking change? I don't remember if there's some subtlety with Type -> impl Into<Type> changes)

Hmm, I think this is theoretically a breaking change because something else might be depending on the type being concrete here. For example, if the caller's doing something like `job.assign_process(handle.into())`, then that would no longer work because the Rust compiler (understandably) can't resolve double-intos.

I don't know how common that is in reality though.

> For handle() and into_handle(), it's possible to return *mut c_void which avoid breaking anything.

Yes -- we can definitely keep returning `*mut c_void`. But if Microsoft's using `isize` as the type, maybe we should bite the bullet, do a breaking change to version 2, and use isize or a newtype wrapper around it ourselves.

re [`JOBOBJECT_EXTENDED_LIMIT_INFORMATION`](https://docs.rs/windows-sys/0.52.0/windows_sys/Win32/System/JobObjects/struct.JOBOBJECT_EXTENDED_LIMIT_INFORMATION.html), I think the best way to handle that is probably to define our own copy of the struct and expose all the fields. It seems relatively straightforward and mechanical. We'd probably want to annotate it as `#[non_exhaustive]` so that consumers can't construct it.

We could just put all or most of the fields in `ExtendedLimitInfo` directly, with maybe the exception of `IoInfo` which is [marked "reserved" on MSDN](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-jobobject_extended_limit_information) anyway.

BTW, [cargo-semver-checks](https://crates.io/crates/cargo-semver-checks) would likely have caught the breakage.
